services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    environment:
      - JENKINS_OPTS=--prefix=/Jenkins

volumes:
  jenkins_home:
